language: node_js
node_js:
- 6
- 8
- 10

addons:
    apt:
        packages:
        - autoconf
        - automake
        - libtool
        - nasm
        - make
        - pkg-config

before_install:
- npm run test:prepare
